#!/usr/bin/env bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && cd ../ && pwd )"

main() {
  cd "${ROOT_DIR}" || exit
  ./tools/set_build_profile target
  docker stop tricore-probe &>/dev/null
  docker rm tricore-probe &>/dev/null
  while docker ps | grep tricore-probe &>/dev/null; do sleep 1; done
  export DEFMT_LOG=trace
  export RUST_LOG=info
  cargo run --features=log_with_defmt --example=$1
}

main $1
