#!/usr/bin/env bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && cd ../ && pwd )"

main() {
  cd "${ROOT_DIR}" || exit
  ./tools/set_build_profile target
  docker rm tricore-probe &>/dev/null && sleep 1
  cargo run --features=example,log_with_defmt --example=$1
}

main $1
