#!/usr/bin/env bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && cd ../ && pwd )"

help() {
  echo "$0 <profile>"
}

assert_exists() {
  local f="${1}"
  if [ ! -e "${f}" ]; then
    help
    exit 1
  fi
}

select_profile() {
  local profile="${1}"

  assert_exists "${ROOT_DIR}/.cargo/config.${profile}.toml"

  cp "${ROOT_DIR}/.cargo/config.${profile}.toml" \
     "${ROOT_DIR}/.cargo/config.toml"

   echo "Select \"${profile}\" profile"
}

main() {
  if [ -z "${1}" ]; then
    help
    exit 1
  fi

  select_profile $1
}

main $1